title = "Alpaca Mount Driver (Telescope)"

[network]
ip_address = ''             # Any address
port = 5555

[server]
location = 'Anywhere on Earth'  # Anything you want here
verbose_driver_exceptions = "True"

[device]
can_reverse = "True"
step_size = 1.0
steps_per_sec = 6
sync_write_connected = "True"     # "True" to emulate sync Connected = "True" (for Conform)
alignment_mode = 1
aperture_area = 0
aperture_diameter = 0
focal_length = 0

equatorial_system = 2
does_refraction = "False"
slew_settle_time = 1
tracking_rates = [123]
axis_rates = []
site_elevation = 0
site_latitude = 0
site_longitude = 0
can_find_home = "True"
can_park = "False"
can_unpark= "False"
can_set_park = "False"
park_pos = [0,0]
can_set_DEC = "True"
can_set_RA = "True"          
can_set_DEC_rate = "False"
can_set_RA_rate= "False"
can_move_axis = "True"
can_slew = "True"
can_slew_async = "False"
can_slew_AltAz = "False"
can_slew_AltAz_async = "False"
can_set_tracking = "True"
can_set_sidereal_rate = "True"
can_pulse_guide = "False"
can_set_guide_rates = "False"
can_sync = "True"
can_sync_AltAz = "False"
can_set_pier_side = "False"

[logging]
log_level = 'INFO'
log_to_stdout = "False"
max_size_mb = 5
num_keep_logs = 10
